name: Habitica Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"

jobs:
  update-readme:
    name: Update habitica stats
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: oleksandryalovyi/todoist-readme@master
        with:
          HABITICA_USER_ID: ${{ secrets.HABITICA_USER_ID }}
          HABITICA_TOKEN: ${{ secrets.HABITICA_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
